# `identifier` and `parent` are linked
[[main]]
  name       = ''
  identifier = 'Github profile yvinc'
  weight     = 4
  url        = 'https://github.com/yvinc'
  pre        = 'github'
  [[main.params]]
    target   = '_blank'

# About me
[[main]]
  name       = 'About :)'
  identifier = 'About me'
  weight     = 1
  url        = 'https://yvinc.github.io/site-experiment/categories/about-me/' # change it
  pre        = 'about'
  [[main.params]]
    target   = '_blank'

# Posts
[[main]]
  name       = 'Posts'
  identifier = 'posts'
  pageRef    = '/'
  weight     = 2

# projects
[[main]]
  name       = 'Projects'
  identifier = 'projects'
  weight     = 3
  url        = 'https://yvinc.github.io/site-experiment/categories/about-me/' # change it
  pre        = 'projects'
  [[main.params]]
    target   = '_blank'

  [[main]]
    name       = 'All Posts'
    identifier = 'all posts'
    pageRef    = '/'
    parent     = 'posts'
    Post       = ''             # preview title in grey
    weight     = 1

  [[main]]
    name       = 'Gallery'
    identifier = 'gallery'
    pageRef    = '/'
    parent     = 'posts'
    Post       = 'some silly stuffs 🤓'
    weight     = 2

# The "More Menu"
[[more]]
  name       = 'Home'
  identifier = 'home'
  pageRef    = '/'
  weight     = 3
  pre        = 'home'


[[more]]
  name       = 'About'
  identifier = 'about'
  pageRef    = '/'
  weight     = 5

  [[more]]
  name       = 'Sustainability'
  identifier = 'sustainability'
  pageRef    = '/'
  parent     = 'about'
  weight     = 1

  [[more]]
  name       = 'Author'
  identifier = 'author'
  pageRef    = '/author'
  parent     = 'about'
  weight     = 2


[[more]]
  name       = 'More Menu'
  identifier = 'more.menu'
  weight     = 99

  [[more]]
    name       = 'That'
    identifier = 'more.menu.that'
    parent     = 'more.menu'

    [[more]]
      name       = 'Never'
      identifier = 'more.menu.that.never'
      parent     = 'more.menu.that'

      [[more]]
        name       = 'Too'
        identifier = 'more.menu.that.never.too'
        parent     = 'more.menu.that.never'

        [[more]]
          name       = 'Deep'
          identifier = 'more.menu.that.never.too.deep'
          parent     = 'more.menu.that.never.too'



[[author-name]]
  name       = ''
  identifier = '@user-name'
  pageRef    = '/'
  weight     = 1
  pre        = 'bluesky'

[[author-name]]
  identifier = 'discord'
  pageRef    = '/'
  weight     = 2
  pre        = 'discord'

[[author-name]]
  name       = ''
  identifier = 'mastodon'
  pageRef    = '/'
  weight     = 3
  pre        = 'mastodon'


[[footer]]
  identifier = 'figma'
  pageRef    = '/'
  weight     = 1
  name       = 'figma'
  pre        = 'figma'

[[footer]]
  identifier = 'hashnode'
  pageRef    = '/'
  weight     = 2
  name       = 'hashnode'
  pre        = 'hashnode'

[[footer]]
  identifier = 'email'
  pageRef    = '/'
  weight     = 3
  name       = 'email'
  pre        = 'email'

[[footer]]
  identifier = 'linkedin'
  pageRef    = '/'
  weight     = 4
  name       = 'linkedin'
  pre        = 'linkedin'

[[footer]]
  identifier = 'karyakarsa'
  pageRef    = '/'
  weight     = 5
  name       = 'karya karsa'
  pre        = 'karyakarsa'

[[contrib]]
  identifier = 'githubsponsors'
  url        = 'https://github.com/sponsors/foxihd/'
  name       = 'Become Github Sponsors'
  pre        = 'githubsponsors'