# `identifier` and `parent` are linked
[[main]]
  name       = ''
  identifier = 'Github profile yvinc'
  weight     = 4
  url        = 'https://github.com/yvinc'
  pre        = 'github'
  [[main.params]]
    target   = '_blank'

# About me
[[main]]
  name       = 'About'
  identifier = 'About me'
  weight     = 1
  pageRef    = '/author/About'
  pre        = 'about'
  [[main.params]]
    target   = '_blank'

# Posts
[[main]]
  name       = 'Posts'
  identifier = 'posts'
  pageRef    = '/'
  weight     = 2

# projects
[[main]]
  name       = 'Projects'
  identifier = 'projects'
  weight     = 3
  pageRef    = '/author'
  pre        = 'projects'
  [[main.params]]
    target   = '_blank'

  [[main]]
    name       = 'All Posts'
    identifier = 'all posts'
    pageRef    = '/post'
    parent     = 'posts'
    Post       = ''             # preview title in grey
    weight     = 1

  [[main]]
    name       = 'Gallery'
    identifier = 'gallery'
    pageRef    = '/'
    parent     = 'posts'
    Post       = 'some silly stuffs 🤓'
    weight     = 2


# The "More Menu"
[[more]]
  name       = 'Home'
  identifier = 'home'
  pageRef    = '/'
  weight     = 3
  pre        = 'home'


[[more]]
  name       = 'About'
  identifier = 'about'
  pageRef    = '/'
  weight     = 5

  [[more]]
  name       = 'Author'
  identifier = 'author'
  pageRef    = '/author'
  parent     = 'about'
  weight     = 2


[[more]]
  name       = 'More Menu'
  identifier = 'more.menu'
  weight     = 99

  [[more]]
    name       = 'That'
    identifier = 'more.menu.that'
    parent     = 'more.menu'

    [[more]]
      name       = 'Never'
      identifier = 'more.menu.that.never'
      parent     = 'more.menu.that'

      [[more]]
        name       = 'Too'
        identifier = 'more.menu.that.never.too'
        parent     = 'more.menu.that.never'

        [[more]]
          name       = 'Deep'
          identifier = 'more.menu.that.never.too.deep'
          parent     = 'more.menu.that.never.too'



[[author-name]] #social icon on About (author) page
  name       = ''
  identifier = '@vincy-huang'
  pageRef    = '/'
  weight     = 1
  pre        = 'bluesky'


[[footer]]
  identifier = 'github'
  weight     = 1
  name       = 'github'
  url        = "https://github.com/yvinc"
  pre        = 'github'
  [[footer.params]]
    target   = "_blank"               # open in new tab (recommended for external)
    rel      = "noopener"             # security best practice

[[footer]]
  identifier = 'email'
  url    = 'mailto:imvincy@outlook.com'
  weight     = 2
  name       = 'email'
  pre        = 'email'
  [[footer.params]]
    target   = "_blank"               # open in new tab (recommended for external)
    rel      = "noopener"             # security best practice  

[[contrib]]
  identifier = 'githubsponsors'
  url        = 'https://github.com/sponsors/foxihd/'
  name       = 'Become Github Sponsors'
  pre        = 'githubsponsors'